### ISSUE TITLE
The link to the genomic data is broken

### ISSUE THREAD

**Issue by carlogs99** [vkola-lab/tmi2024#5]
https://github.com/vkola-lab/tmi2024/blob/main/dataset_csv/README.md

**Comment by Baldwinzc** [comment]
I encountered the same difficulty. May I ask if you have resolved it?

**Comment by GSWS** [comment]
Thank you for bringing this to my attention! I have updated the link to the genomic data. Please check the updated [link](https://drive.google.com/drive/folders/1trUF0lIq1Q72wlJN1cqNZbyubbfNcNd9?usp=drive_link). 
Let me know if you encounter any further issues or have additional questions.
